Window.SetBackgroundTopColor(0.025, 0.055, 0.043);
Window.SetBackgroundBottomColor(0.01, 0.018, 0.016);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - 205);

resales.image = Image("resales-logo.png");
resales.sprite = Sprite(resales.image);
resales.sprite.SetX(Window.GetWidth() / 2 - resales.image.GetWidth() / 2);
resales.sprite.SetY(Window.GetHeight() / 2 + 20);

spinner.image = Image("spinner.png");
spinner.sprite = Sprite(spinner.image);
spinner.sprite.SetX(Window.GetWidth() / 2 - spinner.image.GetWidth() / 2);
spinner.sprite.SetY(Window.GetHeight() / 2 + 125);
spinner.angle = 0;

fun refresh_callback () {
  spinner.angle = spinner.angle + 0.10;
  spinner.sprite.SetImage(spinner.image.Rotate(spinner.angle));
}

Plymouth.SetRefreshFunction(refresh_callback);
